config/routes.rb
ManagerTool::Application.routes.draw do
  root :to => "clients#index"
  get "login/new"
  post "login/check" => "login#check"

  resources :contracts  do 
    resources :sows, shallow: true

     member do
      get  :download
    end
  end
 
  resources :sows do
     member do
      get  :download
    end
  end

  resources :sow_details

  resources :products

  resources :clients do
    member do
      get  :download
    end
  end

  resources :contracts

  resources :salespeople

  resources :users

end

app/models/contract.rb
class Contract < ActiveRecord::Base
	belongs_to :client
	has_many :sows, dependent: :destroy, :order => "id", :conditions => ["deleted is null"]
	has_many :contractfiles, dependent: :destroy,:order => "id"
	has_many :ca_files, dependent: :destroy,:order => "id"
	
	accepts_nested_attributes_for :contractfiles, :reject_if => :child_invalide, :allow_destroy => true 
	accepts_nested_attributes_for :ca_files, :reject_if => :child_invalide,:allow_destroy => true 
	accepts_nested_attributes_for :sows,:allow_destroy => true 


	validates :client_id, presence: true
	validates_presence_of :contractfiles, :if => :is_normal_contract?

	def version
		v = 0
		if contractfiles.empty? ||  contractfiles.count == 0
			v
		else
			Contractfile.find(:all, :conditions =>{:contract_id => self.id }).each do |c|
				v = c.version.to_i if c.version.to_i > v
			end
			v
		end
	end

	def ca_version
		v = 0
		if ca_files.empty? ||  ca_files.count == 0
			v
		else
			CaFile.find(:all, :conditions =>{:contract_id => self.id }).each do |c|
				v = c.version.to_i if c.version.to_i > v
			end
			v
		end
	end

	def product_list
		pl = ''
		 sows.each do |s| 
		 	pl << Product.find(s.product_id).name.upcase << " "
		 end
		if pl.empty?
			pl = "N/A"
		end
		pl
	end

	private

		def child_invalide(attributes)
			attributes.all? do  |key, value| 
				if key == 'version' || key == 'updated_by'
					true
				else
					value.blank?   
				end
			end	
		end

		def is_normal_contract?
			test != true
		end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  # GET /contracts
  # GET /contracts.json
  def index
    session[:current] = 'menu_contracts'

    if ! params[:cid].nil? && params[:cid].to_i > 0
      session[:cid] = params[:cid]
      session[:history] = params[:history]
      @contracts = Contract.where("deleted is null and client_id = #{params[:cid]}")
    else
      session[:cid] = 0
      session[:history] = params[:history]
      @contracts = Contract.find(:all, :order => ' client_id, created_at DESC' )
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contracts }
    end
  end

   def download
    @contract = Contract.find(params[:id])
    
    if params[:type].to_s.downcase == 'contract'
      if params[:version].nil?
        contract_record = @contract.contractfiles.last
      else
        contract_record = Contractfile.where(:contract_id => @contract.id, :version => params[:version]).last
      end
      send_data contract_record.file.read,  :disposition => "inline", :type => "application/pdf", :filename => "#{@contract.client.name}_contract_V#{contract_record.version}.pdf"
    end
    
    if params[:type].to_s.downcase == 'ca'
      if params[:version].nil?
        ca_record =  @contract.ca_files.last
      else
        ca_record = CaFile.where(:contract_id => @contract.id, :version => params[:version]).last
      end
      send_data ca_record.file.read,  :disposition => "inline", :type => "application/pdf", :filename => "#{@contract.client.name}_CA_V#{ca_record.version}.pdf"
    end
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
    session[:current] = 'menu_contracts'
    @contract = Contract.find(params[:id])
    @client = Client.find(@contract.client_id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contract }
    end
  end

  # GET /contracts/new
  # GET /contracts/new.json
  def new
    session[:current] = 'menu_contracts'
    @contract = Contract.new
    @contract.contractfiles.build
    if params[:client_id]
      @client = Client.find(params[:client_id])
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contract }
    end
  end


  # GET /contracts/1/edit
  def edit
    session[:current] = 'menu_contracts'
    @contract = Contract.find(params[:id])
    @contract.contractfiles.build
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(params[:contract])
    if session[:user].nil? 
       redirect_to :controller => "login", :action => "new"
    else
      @contract.updated_by = session[:user]
    end
    

    respond_to do |format|
      if @contract.save
        format.html { redirect_to new_contract_sow_path(@contract) , notice: 'Contract was successfully created.' }
        format.json { render json: @contract, status: :created, location: @contract }
      else
        format.html { render action: "new" }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contracts/1
  # PUT /contracts/1.json
  def update
    @contract = Contract.find(params[:id])
    if session[:user].nil? 
       redirect_to :controller => "login", :action => "new"
    else
      @contract.updated_by = session[:user]
    end

    respond_to do |format|
      if @contract.update_attributes(params[:contract])
        format.html { redirect_to clients_path(:clientid => @contract.client_id), notice: 'Contract was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract = Contract.find(params[:id])
    #@contract.destroy
    if session[:user].nil? 
      redirect_to :controller => "login", :action => "new"
    else
      @contract.updated_by = session[:user]
      @contract.deleted = true
    end
    @contract.sows.each do |s|
      s.updated_by = session[:user]
      s.deleted = true
    end
    @contract.save

    respond_to do |format|
      if params[:permanent] == '1'
        format.html { redirect_to clients_path(:clientid => @contract.client_id) }
        format.json { head :ok }
      else
        format.html { redirect_to clients_path(:clientid => @contract.client_id) }
        format.json { head :ok }
      end
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
	def us_states
	    [
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
end

app/views/contracts/_form.html.erb
<%= form_for(@contract, :html => {:multipart => true}) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :client%>
    <% if ! @client.nil? %>
      <%= collection_select(:contract, :client_id, [@client], :id, :name_with_state,{}) %>
    <% else %>
      <%= collection_select(:contract, :client_id, Client.find(:all), :id, :name_with_state, {:prompt => 'Please select the client'}) %>
    <%end%>
  </div>

  <div class="field">
      <%= f.label :test, "Test?" ,:id=>"test" %> 
      <%= f.label :yes, "yes" %> 
      <%= f.check_box :test ,:style => "float:left;"  %> 
  </div> <br><br><br>   <br><br><br>  

   <%= f.fields_for :contractfiles, f.object.contractfiles.build  do |builder| %>
    <p><%= builder.file_field :file %></p>
    <p><%= builder.hidden_field :file_cache %></p>
    <p><%= builder.hidden_field :version, :value => ( @contract.version + 1 ) %></p>
    <%= builder.hidden_field :updated_by, :value => session[:user] %>
  <% end %><br />



  <div id="ca_part">
    <div class="field" >
      <%= f.label :credit_aggrement, "Sign CA" ,:id=>"ca" %> 
      <%= f.label :yes, "yes" %> 
      <%= f.check_box :ca_flag ,:style => "float:left;", :id=>"casign" %> 
      <br><br><br>  
    </div>  

  <fieldset  id="cadate" >
    <div class="field" >
      <%= f.label "casenddate", "CA send date",:id=>"casend"  %>
      <%= f.datepicker :ca_send_at  %>  <br><br><br>  
      <%= f.label "casigndate","CA executed date",:id=>"casigndate"  %> 
      <%= f.datepicker :ca_executed_at  %>   <br><br><br> 
    </div>  
    <%= f.fields_for :ca_files, f.object.ca_files.build  do |builder| %>
      <p><%= builder.file_field :file %></p>
      <p><%= builder.hidden_field :file_cache %></p>
      <p><%= builder.hidden_field :version, :value => ( @contract.ca_version + 1 ) %></p>
      <%= builder.hidden_field :updated_by, :value => session[:user] %>
    <% end %><br /><br> 
  </fieldset>
</div>  
   
 
  <div class="field">
    <%= f.label :comment %> 
    <%= f.text_field :comment %>
  </div><br><br>

 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
<script>
$(".popover-tx").popover();
$('#casend').tooltip({'trigger':'click hover focus', 'title': 'The date on which we send credit agreement to the client' });
  $('#ca').tooltip({'trigger':'click hover focus', 'title': 'Please check this checkbox if you need sign credit agreement' });
  $('#casigndate').tooltip({'trigger':'click hover focus', 'title': 'The date on which we sign credit agreement' });


  $(function(){
     if ( $("#casign").is(':checked') ) {
        $("#cadate").show();
     } else {
      $("#cadate").hide();
    }

     $('#casign').click(function(){
      $("#cadate").slideToggle();
    });

  });

</script>

app/views/contracts/edit.html.erb
<div class="span1">
</div>
<div class="span11">
<br /><br /><br />
<h1>Upload new version</h1><br />

<%= render 'form' %>

 
 
<%= link_to 'Back', clients_path(:clientid=>@contract.client.id) %>
</div>

app/views/contracts/index.html.erb
 
<!--Body content-->

     <br /><br />
    <h1>Listing Contracts </h1> 

    <!-- <div>         
            <button id="enable" class="btn btn-small">enable/disable edit</button>
    </div>  
 -->
    <br /><br />


    <form class="form-inline " method="get">
          <ul class="nav nav-pills">
          <li>
            <label>Client...</label>
                <% option_status = Client.clients_id_and_name %>
                <%= select_tag("cid", options_for_select(option_status, session[:cid]), :prompt => 'Please select') %>
              </li>
              <li>
                <label>History...</label>
                <% option_name = ["All","Current"]%>
                <% if  session[:history].nil? %>
                    <%= select_tag("history", options_for_select(option_name,"Current")) %>
                <% else %>
                    <%= select_tag("history", options_for_select(option_name,session[:history])) %>
                <% end %>
              </li>

              <li class='active'>
                <input type="submit" value="Filter" style="margin: 0px  0px  0px  10px;" />
              </li>
            </ul>
    </form> <br \>  

    <% if session[:cid] && session[:history] %>

    <table id="tb" class="stats" style="width: 100%">
        <thead>
        <tr>
            <th class='hed'>Client </th>
            <th class='hed'>Product </th>
            <%if @permanent == '1'%>
                    <th class='hed'>Contract execute date </th> 
            <% end %>
            <th class='hed'>Real cust_id </th>
            <!-- <th class='hed'>Sales </th> -->
            <th class='hed'>Creating date </th>
          <!--   <th class='hed'>Send date </th>
            <th class='hed'>Sign date </th> -->
            <th class='hed'>Version </th>
            <th class='hed'>Uploade </th>
            <!--
            <th class='hed'>BAA date </th>
            <th class='hed'>Contract execute date </th>
            <th class='hed'>Status </th>
            <th class='hed'>Comment </th>
            -->
            <th class='hed'>Delete </th>
            <th class='hed'>View SOW </th>
        </tr>
        </thead>
        <tbody>

            <% @contracts.each do |contract| %>
              <tr>
                
                <td><%= contract.client.name_with_state %></td>
                <td><%= contract.product_list %></td>
                <%if @permanent == '1'%>
                    <td><%= contract.contract_execute_date %></td>
                <% end %>
                 <td>
                    <% if contract.client.cust_id.nil?  %>
                        N/A
                    <% else %>
                        <%= contract.client.cust_id %>
                    <% end %>
                 </td>
                <!--  <td><%= contract.client.list_of_sales %></td> -->
                <td>
                   <%= contract.created_at %>
                </td>
                <!-- <td>
                    <div id="contract_send_at" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= contract.id%>" data-value = "<%= contract.contract_send_at %>" >
                    </div>
                </td>

                <td>
                    <div id="contract_sign_at" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= contract.id%>" data-value = "<%= contract.contract_sign_at %>" >
                    </div>
                </td> -->
                 
                <td>
                    <% if contract.contractfiles.empty? %>
                        N/A
                    <% else %>
                        <% if session[:history].nil? || session[:history].upcase == 'CURRENT'  %>
                            <%= " V#{contract.contractfiles.count}  " %>
                            <%= link_to raw('<i class=" icon-download" ></i>'), "#{contract.contractfiles.last.file}" %> 
                        <% else %>
                            <% count = 1 %>
                            <% contract.contractfiles.each do |f| %>
                                <%= " V#{count}  " %>
                                <%= link_to raw('<i class=" icon-download" ></i>'), "#{f.file}" %> 
                                <% count = count + 1 %>
                                <br />
                            <% end %>
                        <% end %>
                    <% end %>
                </td>
                <td>
                    <%= link_to raw('<i class="icon-upload"></i>'), edit_contract_path(contract)  %>
                </td>

                
                <%if @permanent == '1'%>
                    <td><%= link_to raw('<i class="icon-trash "></i>'), contract_path(contract,:permanent => '1'),  method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% else %>
                    <td><%= link_to raw('<i class="icon-trash "></i>'), contract_path(contract) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>

                <td>
                    <%= link_to raw('<i class="icon-eye-open"></i>'), contract_sows_path(contract)  %>
                </td>
                 
              </tr>
            <% end %>
         </tbody>
    </table>

    <% else %>
    <% end %>
    <br />

    <script>
        $(function(){
            $('.ct_date').editable({
                ajaxOptions: {
                    type: 'PUT'
                },
                format: 'yyyy-mm-dd',    
                viewformat: 'dd/mm/yyyy',    
                datepicker: {
                        weekStart: 1
                }

            });
            $('#enable').click(function() {
                $('#tb .editable').editable('toggleDisabled');
            });  
            $('.ct_description').editable({
                ajaxOptions: {
                    type: 'PUT'
                },
                title: 'Enter Description',

            });
                    $('#tb .editable').editable('toggleDisabled');
        });
    </script>
 

app/views/contracts/new.html.erb
<div class="span1">
</div>
<div class="span11">
<div id="box">
<div style="margin-top:30px">
	<h2>Add new contract</h2>
	<span style="color: red" > </span>
	<%= render 'form' %>

	<!--! end of #container <%= link_to 'Back', contracts_path %> -->
</div>
</div>
</div>

app/views/contracts/newwithclient.html.erb
<div class="span1">
</div>
<div class="span11">
<div id="box">
<div style="margin-top:30px">
	<h2>Add new contract</h2>
	<span style="color: red" > </span>
	<%= render 'form' %>

	<!--! end of #container <%= link_to 'Back', contracts_path %> -->
</div>
</div>
</div>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Client name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Client state:</b>
  <%= @client.state %>
</p>

<p>
  <b>Client email:</b>
  <%= @client.email %>
</p>




<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>