config/routes.rb
ManagerTool::Application.routes.draw do
  root :to => "clients#index"
  get "login/new"
  post "login/check" => "login#check"

  resources :contracts  do 
    resources :sows, shallow: true

     member do
      get  :download
    end
  end
 
  resources :sows do
     member do
      get  :download
    end
  end

  resources :sow_details

  resources :products

  resources :clients do
    member do
      get  :download
    end
  end

  resources :contracts

  resources :salespeople

  resources :users

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :contracts, dependent: :destroy, :order => "id",:conditions => ["deleted is null"]
	has_many :baafiles, dependent: :destroy, :order => "id"
	has_many :ndafiles, dependent: :destroy, :order => "id"
	has_many :sales, dependent: :destroy
	has_many :salespeople, through: :sales


	accepts_nested_attributes_for :contracts, :sales, :salespeople, :baafiles, :ndafiles
	accepts_nested_attributes_for :baafiles,  :reject_if => :child_invalide,:allow_destroy => true 
	accepts_nested_attributes_for :ndafiles,  :reject_if => :child_invalide,:allow_destroy => true 

	def baa_version
		v = 0
		if baafiles.empty? ||  baafiles.count == 0
			v
		else
			Baafile.find(:all, :conditions =>{:client_id => self.id }).each do |b|
				v = b.version.to_i if b.version.to_i > v
			end
			v
		end
	end

	def nda_version
		v = 0
		if ndafiles.empty?  ||  ndafiles.count == 0
			v
		else
			Ndafile.find(:all, :conditions =>{:client_id => self.id }).each do |n|
				v = n.version.to_i if n.version.to_i > v
			end
			v
		end
	end

	def name_with_state
		if city.nil? or city =~ /^\s*$/
			"#{name}: #{state}"
		else
			"#{name}: #{city}, #{state}"
		end
  	end

  	def list_of_sales
  		ls = '';
		if ! salespeople.empty?  
		  salespeople.each do |s|
			ls << "#{s.first_name} #{s.last_name}" << ';'
		  end
		end
		return ls
  	end

  	def ids_of_sales
  		ids = Array.new;
		if ! salespeople.empty?  
		  salespeople.each do |s|
			ids << s.id
		  end
		end
		return ids.join(",")
  	end

  	def self.clients_id_and_name
  		option_list = Array.new();
  		#option_list << ["All", 0];
  		Client.find(:all).each do |c|
  			option_list << ["#{c.name_with_state.upcase}", c.id]
  		end
  		option_list.sort
  	end

  	validates :name, presence: true
  	validates :salesperson_ids, presence: true
  	validates :cust_id, :numericality => { :greater_than_or_equal_to => 0 }, :allow_nil => true
  	validates :phone, :allow_blank => true, :allow_nil => true, :numericality => true,:length => { :minimum => 10, :maximum => 15 }   
  	validates_format_of :email, :allow_blank => true, :presence => false, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i


  	private

		def child_invalide(attributes)
			attributes.all? do  |key, value| 
				if key == 'version' || key == 'updated_by'
					true
				else
					value.blank?   
				end
			end	
		end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
   

    session[:current] = 'menu_clients'
    if params[:clientid].nil? || params[:clientid].to_s.empty?
      @clients = Client.all
      session[:clientid] = 0
    else
      @clients = Client.where(:id=>params[:clientid])
      session[:clientid] = params[:clientid]
    end
    
    session[:history] = 'current'
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  def download
    @client = Client.find(params[:id])
    
    if params[:type].to_s.downcase == 'baa'
      if params[:version].nil?
        baa_record = @client.baafiles.last
      else
        baa_record = Baafile.where(:client_id => @client.id, :version => params[:version]).last
      end
      send_data baa_record.file.read,  :disposition => "inline", :type => "application/pdf", :filename => "#{@client.name}_BAA_V#{baa_record.version}.pdf"
    end
    
    if params[:type].to_s.downcase == 'nda'
      if params[:version].nil?
        nda_record = @client.ndafiles.last
      else
        nda_record = Ndafile.where(:client_id => @client.id, :version => params[:version]).last
      end
      send_data nda_record.file.read,  :disposition => "inline", :type => "application/pdf", :filename => "#{@client.name}_NDA_V#{baa_record.version}.pdf"
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    session[:current] = 'menu_clients'
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    session[:current] = 'menu_clients'
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])
    if session[:user].nil? 
       redirect_to :controller => "login", :action => "new"
    else
      @client.updated_by = session[:user]
    end

    respond_to do |format|
      if @client.save
        format.html { redirect_to new_contract_path(:client_id=>@client.id), notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])
    if session[:user].nil? 
       redirect_to :controller => "login", :action => "new"
    else
      @client.updated_by = session[:user]
    end

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to clients_path(:clientid => @client.id), notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
	def us_states
	    [
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
end

app/views/clients/_edit_form.html.erb
<%= form_for(@client, :html => { :multipart => true }) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <fieldset>

  <div class="field" > 
    <%= f.label :bsd, "BAA send date" , :id=>"baa" %> 
    <%= f.datepicker :baa_send_at  %> 
    <br><br><br>  
  </div>  
  <div class="field">
    <%= f.label :bid, "BAA executed date", :id=>"baasign" %> 
    <%= f.datepicker :baa_executed_at  %>  
  </div>  <br>
   <% last_baa = @client.baafiles.last %>
   <%= f.fields_for :baafiles, @client.baafiles.build  do |builder| %>
    <p><%= builder.file_field :file %></p>
    <% if last_baa.nil? %>
     <p><%= builder.hidden_field :version, :value => 1 %></p>
    <% else %>
     <p><%= builder.hidden_field :version, :value => (last_baa.version + 1 )%></p>
    <% end %>
    <%= builder.hidden_field :updated_by, :value => session[:user] %>
    <p><%= builder.hidden_field :file_cache %></p>
  <% end %><br /> 
  </fieldset>

  <div class="field">
    <%= f.label :sn, "Sign NDA ?" , :id=>"nda" %> 
    <%= f.label :yes, "yes"   %> 
    <%= f.check_box :nda_flag ,:style => "float:left;", :id=>"ndacheck"%> 
    <br><br><br>  
  </div>  

  <fieldset  id="ndadate" >
  <div class="field" >
    <%= f.label :nsd, "NDA send date"  %>
    <%= f.datepicker :nda_send_at  %>  <br /><br /><br />  
    <%= f.label :nid, "NDA executed date"  %> 
    <%= f.datepicker :nda_executed_at  %>   
  </div>  <br /> <br /> 
  <% last_nda = @client.ndafiles.last %>
  <%= f.fields_for :ndafiles, @client.ndafiles.build  do |builder| %>
    <p><%= builder.file_field :file %></p>
     <% if last_nda.nil? %>
     <p><%= builder.hidden_field :version, :value => 1 %></p><br /> 
    <% else %>
     <p><%= builder.hidden_field :version, :value => (last_nda.version + 1 )%></p>
    <% end %>
    <%= builder.hidden_field :updated_by, :value => session[:user] %>
    <p><%= builder.hidden_field :file_cache %></p>
  <% end %><br />
  </fieldset><br /> <br /> 


 
  <div class="actions">
    <%= f.submit "Submit" %>
  </div><br /> <br /> 
<% end %>

<script>
$('#contact').tooltip({'trigger':'click hover focus', 'title': 'Please input the client contact name here' });
  $('#baa').tooltip({'trigger':'click hover focus', 'title': 'The date on which we send business associate agreement to the client' });
  $('#baasign').tooltip({'trigger':'click hover focus', 'title': 'The date on which we sign business associate agreement' });
  $('#nda').tooltip({'trigger':'click hover focus', 'title': 'Please check this checkbox if you need sign non-disclosure agreement' });
  $('#ndasign').tooltip({'trigger':'click hover focus', 'title': 'The date on which we sign non-disclosure agreement' });

  $(function(){
    

    if ($('#ndacheck').is(':checked')) {
        $("#ndadate").show();
    } else {
        $("#ndadate").hide();
    } 

    $('#ndacheck').click(function(){
      $("#ndadate").slideToggle();
    });

  });

</script>

app/views/clients/_showsow.html.erb
 <h2>SOW Info </h2>
    <% if contract.nil? %>
        <p> N/A </P>
    <% else %>
        <% contract.sows.each do |sow| %>
            <table id="tb" class="table  table-condensed table-hover mytable" cellspacing="0">
                <tbody>
                    <tr>
                        <td class='hed'>SOW #: </td>
                        <td><span class="badge badge-info"><%= contract.sows.index(sow) + 1 %></span> </td>
                    </tr>
                    <tr>
                        <td class='hed'>Product: </td>
                        <td><span class="badge badge-info"><%= sow.product %></span> </td>
                    </tr>  
                    <tr>
                        <td class='hed'>Send date: </td>
                        <td>
                            <div id="sow_send_at" class="sow_date" data-resource="sow" data-type="date" data-pk="1"  data-url="/sows/<%= sow.id%>" data-value = "<%= sow.sow_send_at %>" >
                            </div>
                        </td>
                       <!--  <td>
                            <a href="#" id="sow_send_at" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_send_at %></a>    
                        </td> -->
                    </tr>  
                    <tr>
                        <td class='hed'>Executed date: </td>
                        <td>
                            <a href="#" id="sow_executed_at" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_executed_at %></a>    
                        </td>
                    </tr>  
                    <tr>
                        <td class='hed'>Kickoff date: </td>
                        <td>
                            <a href="#" id="sow_ko_date" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_ko_date %></a>    
                        </td>
                    </tr>  
                    <tr>
                        <td class='hed'>Production date: </td>
                        <td>
                            <a href="#" id="sow_production_date" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_production_date %></a>    
                        </td>
                    </tr>  
                    <tr>
                        <td class='hed'>Start date: </td>
                        <td>
                            <a href="#" id="sow_start_date" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_start_date %></a>    
                        </td>
                    </tr> 
                    <tr>
                        <td class='hed'>End date: </td>
                        <td>
                            <a href="#" id="sow_end_date" class="sow_date" data-resource="sow" data-type="date" data-pk="1" data-url="/sows/<%= sow.id %>"  data-original-title="Select date"><%= sow.sow_end_date %></a>    
                        </td>
                    </tr> 

                    <tr>
                        <td class='hed'>Auto renew: </td>
                        <td>
                            <a href="#" id="auto_renew" class="sow_yn"  data-resource="sow" data-type="select" data-pk="1" data-url="/sows/<%= sow.id %>" data-original-title="Select status"><%= sow.auto_renew %></a> 
                        </td>
                    </tr>

                    <tr>
                        <td class='hed'>Accept term(mo): </td>
                        <td>
                            <a href="#" id="accept_term" class="sow_int"  data-resource="sow" data-type="select" data-pk="1" data-url="/sows/<%= sow.id %>" data-original-title="Select status"><%= sow.accept_term %></a>   
                        </td>
                    </tr>

                    <tr>
                        <td class='hed'>File: </td>
                        <% count = sow.sow_files.last.version %>
                        <td>
                            <% if session[:history].nil? || session[:history].upcase == 'CURRENT'  %>
                                <% if sow.sow_executed_at.nil? %>
                                        <span class="badge badge-important" id="sow_badge">
                                    <% else %>
                                        <span class="badge badge-success" id="sow_badge">
                                    <% end %>
                                    <%= " V#{sow.version}  " %>
                                    <%= link_to raw('<i class=" icon-download icon-white" ></i>'), download_sow_path(sow, :version=>sow.version) %>
                                 </span>
                            <% else %>
                                <% sow.sow_files.each do |f| %>
                                    <% if f.version == count %>
                                        <span class="badge badge-important">
                                    <% else %>
                                        <span class="badge ">
                                    <% end %>
                                    <%= " V#{f.version}  " %>
                                    <% if f.version == count %>
                                        <%= link_to raw('<i class=" icon-download icon-white" ></i>'), download_sow_path(sow, :version=>sow.version)  %> 
                                    <% else %>
                                        <%= link_to raw('<i class=" icon-download icon-white" ></i>'), download_sow_path(sow, :version=>sow.version) %> 
                                    <% end %>
                                    </span>
                                    <br />
                                <% end %> 
                            <% end %>
                        </td>
                    </tr> 
                    <tr>
                        <td class='hed'>New version: </td>
                         <td>
                            <span class="badge  badge-inverse">
                            <%= link_to raw('<i class="icon-upload  icon-white"></i>'), edit_sow_path(sow,:contract_id=>contract.id)   %>
                            </span>
                        </td>
                    </tr>               
                    <tr>
                        <td class='hed'>Create Date: </td>
                        <td> <%= sow.created_at %>  </td>
                    </tr> 
                     <tr>
                        <td class='hed'>Delete </td>
                        <td><%= link_to raw('<i class="icon-trash "></i>'), sow, confirm: 'Are you sure?', method: :delete %></td>
                    </tr>

                </tbody>
            </table>  <br />
        <% end %>
        <p> <%=link_to "New Sow",  new_contract_sow_path(contract) %></p>
    <% end %>

app/views/clients/edit.html.erb
<div class="span1">
</div>
<div class="span11">
	<br /><br /><br />
<h1>Upload new version</h1><br />

<%= render 'edit_form' %>

 
<%= link_to 'Back', clients_path(:clientid=>@client.id) %>
</div>

app/views/clients/index.html.erb
 <!--Body content-->
    <div id="container" class="container-fluid">
        <div class="row-fluid">
            <br \>

            <div class="span4" >

                 <form class="form-inline " method="get">
                      <ul class="nav nav-pills">
                        <li>
                            <h1>
                                <span class="label label-warning">CLIENT
                                <% option_status = Client.clients_id_and_name %>
                                <%= select_tag("clientid", options_for_select(option_status, session[:clientid]), :id=>"myclient", :prompt => "Please select") %> </span>
                            </h1>
                        </li>
                      </ul>
                </form>    
               
        
            </div> 
            <div class="span8">
                
                   
                   
                 
            </div><!--end of span9-->
        </div><!--end of row--> <br \> 

        

        <% if session[:clientid].to_s == '0' %>
           
            <!-- <div id="table-container" style="overflow:auto; height: 500px;"> -->
            <!--<table id="tb" class="table  table-condensed table-hover table-bordered" cellspacing="1" style="margin-right:50px;" >
                <thead>
                  <tr>
                    <th class="hed">Name </th>
                    <th class="hed">State </th>
                     <th class="hed">City </th>
                    <th class="hed">Cust_id </th>
                    <th class="hed">BAA send date </th>
                    <th class="hed">BAA sign date </th>
                    <th class="hed">NDA send date </th>
                    <th class="hed">NDA sign date </th>
                    <th class="hed">Contact Name </th>
                    <th class="hed">Contact Phone </th>
                    <th class="hed">Contact Email </th>
                    <th class="hed">Sales </th>
                    <th class="hed">View Contracts </th>
                    <th class="hed">Delete</th>
                  </tr>
                </thead>
                <tbody>
                    <% @clients.each do |client| %>
                      <tr>
                        <td><%= client.name %></td>
                        <td><%=  client.state %></td>
     
                        <td>
                             <div id="city" class="cityname" data-resource="client" data-type="text" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.city %>" >
                            </div>
                        </td> 

                        <td>
                             <div id="cust_id" class="ct_date" data-resource="client" data-type="text" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.cust_id %>" >
                            </div>
                        </td> 

                        <td>
                             <div id="baa_send_at" class="ct_date" data-resource="client" data-type="date" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.baa_send_at %>" >
                            </div>
                        </td>
                        <td>
                             <div id="baa_sign_at" class="ct_date" data-resource="client" data-type="date" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.baa_sign_at %>" >
                            </div>
                        </td>
                        <% if client.nda_flag == false %>
                            <td><%= client.nda_send_at %>N/A</td>
                            <td><%= client.nda_sign_at %>N/A</td>
                        <% else %>
                             <td>
                                <div id="nda_send_at" class="ct_date" data-resource="client" data-type="date" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.nda_send_at %>" >
                                </div>
                             </td>
                             <td>
                                <div id="nda_sign_at" class="ct_date" data-resource="client" data-type="date" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.nda_sign_at %>" >
                                </div>
                             </td>
                        <% end %>

                        <td>
                             <div id="contact_name" class="contactname" data-resource="client" data-type="text" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.contact_name %>" >
                            </div>
                        </td> 

                        <td>
                             <div id="phone" class="phonenum" data-resource="client" data-type="text" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.phone %>" >
                            </div>
                        </td> 

                        <td>
                             <div id="email" class="emailaddress" data-resource="client" data-type="text" data-pk="1"  data-url="/clients/<%= client.id%>" data-value = "<%= client.email %>" >
                            </div>
                        </td> 

                        <td>
                             <div id="salesperson_ids" class="sp" data-resource="client" data-type="checklist" data-pk="1"  data-url="/clients/<%= client.id%>"  
                                 data-value = [<%= client.ids_of_sales %>] data-original-title="Select Salespeople" >
                            </div>
                        </td> 

                   
                        <td><%= link_to raw('<i class="icon-eye-open"></i>'), contracts_path(:cid=>client.id) %></td>
                        <td><%= link_to raw('<i class="icon-trash "></i>'), client, confirm: 'Are you sure?', method: :delete %></td>
                      </tr>
                    <% end %>
                </tbody>
            </table> -->
        <% else %>
         <button id="enable" class="btn btn-small">Enable Edit</button>
             <%= render 'showbox' %>
        <% end %>

        <br />
    </div> <!--! end of #container -->

    <script>
 
    $(function(){
        $('.ct_date').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            format: 'yyyy-mm-dd',    
            viewformat: 'mm/dd/yyyy',    
            datepicker: {
                    weekStart: 1
            }

        });

        $('.clientname').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter Client Name',

        });

        $('.cityname').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter City Name',

        });

        $('.contactname').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter Contact Name',

        });

        $('.phonenum').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter Phone Number',

        });

        $('.emailaddress').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter Email Address',

        });

        $('.sp').editable({   
            source: [
            <% Salesperson.find(:all).each do |p| %>
                {value: <%= p.id %>, text: <%="'#{p.first_name} #{p.last_name}'".gsub(/&/, "&amp;").gsub(/\"/, "&quot;").html_safe %>},
            <% end %>  
            ]
        });

         $('.sow_date').editable({
            format: 'yyyy-mm-dd',    
            viewformat: 'mm/dd/yyyy',    
           // mode: 'inline',
            datepicker: {
                    weekStart: 1
               }
        });

        $('.sow_yn').editable({
            source: [
                  {value: 'Y', text: 'Y'},
                  {value: 'N', text: 'N'},
               ]
        });

        $('.sow_int').editable({
            mode: 'inline',
            source: [
                  {value: 1, text: '1'},
                  {value: 2, text: '2'},
                  {value: 3, text: '3'},
                  {value: 4, text: '4'},
                  {value: 5, text: '5'},
                  {value: 6, text: '6'},
                  {value: 7, text: '7'},
                  {value: 8, text: '8'},
                  {value: 9, text: '9'},
                  {value: 10, text: '10'},
                  {value: 11, text: '11'},
                  {value: 12, text: '12'},
                  {value: 13, text: '13'},
                  {value: 14, text: '14'},
                  {value: 15, text: '15'},
               ]
        });

        $('.statelist').editable({   
          source: [
               
              <% us_states.each do |st| %>
                {value: '<%= st[1] %>', text: '<%= st[0] %>'},
               
              <% end %>
             ]
        });

        $('.commenttext').editable({
          url: '/post',
          title: 'Enter comments',
          rows: 16,
         display: function(value, response) {
              if(! response && ! value ) { $(this).empty();}
              else {
                $(this).html(value.substring(0,30) + '...');
              }
          }
        });


        $('#enable').click(function() {
            $('#tb .editable').editable('toggleDisabled');
            $(this).text(function(i, text){
                return text === "Enable Edit" ? "Disnable Edit" : "Enable Edit";
            })

            //change baa version badge
            if ( $('#baa_executed_at').text() == "" || $('#baa_executed_at').text() == "Empty" ) {
                $('#baa_badge').addClass('badge-important').removeClass('badge-success');
            } else {
                $('#baa_badge').addClass('badge-success').removeClass('badge-important');
            }

            //change contract version badge
            if ( $('#contract_executed_at').text() == "" || $('#contract_executed_at').text() == "Empty" ) {
                $('#contract_badge').addClass('badge-important').removeClass('badge-success');
            } else {
                $('#contract_badge').addClass('badge-success').removeClass('badge-important');
            }

             //change CA version badge
            if ( $('#ca_executed_at').text() == "" || $('#ca_executed_at').text() == "Empty" ) {
                $('#ca_badge').addClass('badge-important').removeClass('badge-success');
            } else {
                $('#ca_badge').addClass('badge-success').removeClass('badge-important');
            }

             //change sow version badge
            if ( $('#sow_executed_at').text() == "" || $('#sow_executed_at').text() == "Empty" ) {
                $('#sow_badge').addClass('badge-important').removeClass('badge-success');
            } else {
                $('#sow_badge').addClass('badge-success').removeClass('badge-important');
            }

             //change sow version badge
            if ( $('#nda_executed_at').text() == "" || $('#nda_executed_at').text() == "Empty" ) {
                $('#nda_badge').addClass('badge-important').removeClass('badge-success');
            } else {
                $('#nda_badge').addClass('badge-success').removeClass('badge-important');
            }
        });  

        $('#myclient').change(function() {
            this.form.submit();
        });

        $('#tb .editable').editable('toggleDisabled');

    });
</script>

app/views/clients/new.html.erb
<div class="span1">
</div>
<div class="span11">
<div id="box">
	<div style="margin-top:30px">
	<h2>Add a new client</h2>
<span style="color: red" > </span>
	<%= render 'form' %>

	<!--! end of #container <%= link_to 'Back', contracts_path %> -->
</div>
</div>
</div>

app/views/clients/newwithclient.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>State:</b>
  <%= @client.state %>
</p>

<p>
  <b>Cust:</b>
  <%= @client.cust_id %>
</p>

<p>
  <b>Phone:</b>
  <%= @client.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Comment:</b>
  <%= @client.comment %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Clients List', clients_path %> |
<%= link_to 'Generate contract', new_contract_path() %>