config/routes.rb
ManagerTool::Application.routes.draw do
  root :to => "clients#index"
  get "login/new"
  post "login/check" => "login#check"

  resources :contracts  do 
    resources :sows, shallow: true

     member do
      get  :download
    end
  end
 
  resources :sows do
     member do
      get  :download
    end
  end

  resources :sow_details

  resources :products

  resources :clients do
    member do
      get  :download
    end
  end

  resources :contracts

  resources :salespeople

  resources :users

end

app/models/sow.rb
class Sow < ActiveRecord::Base
	
	
	has_many :autointel_rates, dependent: :destroy,:order => "id"
	has_many :sow_files, dependent: :destroy,:order => "id"
	has_many :charity_rates, dependent: :destroy,:order => "id"
	has_many :payment_rates, dependent: :destroy,:order => "id"
	has_many :payorintel_rates, dependent: :destroy,:order => "id"
	belongs_to :contract
	 
	validates :product_id, presence:true
	 

	validates_presence_of :sow_files
	validates_presence_of :payorintel_rates, :if => :is_payorintel?
	validates_presence_of :payment_rates, :if => :is_payment?
	validates_presence_of :charity_rates, :if => :is_charity?
	validates_presence_of :autointel_rates, :if => :is_autointel?
	
	
 
	accepts_nested_attributes_for :sow_files,  :allow_destroy => true 
	accepts_nested_attributes_for :autointel_rates, :reject_if => :child_invalide, :allow_destroy => true 
	accepts_nested_attributes_for :charity_rates, :reject_if => :child_invalide, :allow_destroy => true 
	accepts_nested_attributes_for :payment_rates,  :reject_if => :child_invalide,:allow_destroy => true 
	accepts_nested_attributes_for :payorintel_rates, :reject_if => :child_invalide, :allow_destroy => true 


	def version
		v = 0
		if sow_files.empty? ||  sow_files.count == 0
			v
		else 
			SowFile.find(:all, :conditions =>{:sow_id => self.id }).each do |s|
				v = s.version.to_i if s.version.to_i > v
			end
			v
		end
	end

	def product
		Product.find(product_id).name.upcase  
	end	 

	private


		def child_invalide(attributes)
			attributes.all? do  |key, value| 
				if key == 'version'
					true
				else
					value.blank?   
				end
			end	
		end

		def is_payorintel?
			 
  			if Product.find(product_id).name.upcase == 'PAYORINTEL'
  				true
  			else
  				false
  			end
		end

		def is_payment?
  			if Product.find(product_id).name.upcase =~ /PAYMENT/
  				true
  			else
  				false
  			end
		end

		def is_charity?
  			if Product.find(product_id).name.upcase =~ /CHARITY/
  				true
  			else
  				false
  			end
		end

		def is_autointel?
  			if Product.find(product_id).name.upcase =~ /AUTOINTEL/
  				true
  			else
  				false
  			end
		end

end

app/controllers/sows_controller.rb
class SowsController < ApplicationController
  # GET /sows
  # GET /sows.json
  def index
    @contract = Contract.find(params[:contract_id])
    @sows = Sow.find(:all, :conditions => [ "deleted is null and contract_id = ?", params[:contract_id] ] )

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sows }
    end
  end

  def download
    @sow = Sow.find(params[:id])
    
     
    if params[:version].nil?
      sow_record = @sow.sow_files.last
    else
      sow_record = SowFile.where(:sow_id => @sow.id, :version => params[:version]).last
    end
    send_data sow_record.file.read,  :disposition => "inline", :type => "application/pdf", :filename => "#{@sow.contract.client.name}_sow_V#{sow_record.version}.pdf"  
  end

  # GET /sows/1
  # GET /sows/1.json
  def show
    @sow = Sow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sow }
    end
  end

  # GET /sows/new
  # GET /sows/new.json
  def new
    @sow = Sow.new
    @sow.sow_files.build
    @contract = Contract.find(params[:contract_id])
    @path = [@contract,@sow]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sow }
    end
  end

  # GET /sows/1/edit
  def edit
    @sow = Sow.find(params[:id])
    @path = @sow
    @contract = @sow.contract
  end

  # POST /sows
  # POST /sows.json
  def create
    @sow = Sow.new(params[:sow])
    @sow.contract = Contract.find(params[:contract_id])
    if session[:user].nil? 
       redirect_to :controller => "login", :action => "new"
    else
      @sow.updated_by = session[:user]
    end
    
    respond_to do |format|
      if @sow.save
        
          format.html { redirect_to new_contract_sow_path(@sow.contract), notice: 'Sow was successfully created.' }
          format.json { render json: @sow, status: :created, location: @sow }
      else
        @contract = Contract.find(params[:contract_id])
        @path = [@contract,@sow]
        format.html { render action: "new" }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sows/1
  # PUT /sows/1.json
  def update
  @sow = Sow.find(params[:id])
  if session[:user].nil? 
     redirect_to :controller => "login", :action => "new"
  else
    @sow.updated_by = session[:user]
  end


    respond_to do |format|

      if @sow.update_attributes(params[:sow])

        format.html { redirect_to clients_path(:clientid => @sow.contract.client_id), notice: 'Sow was successfully created.' }
        format.json { head :no_content }
      else
        @contract = Contract.find(@sow.contract_id)
        @path = @sow
        format.html { render action: "edit"  }
        format.json { render json: @sow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sows/1
  # DELETE /sows/1.json
  def destroy
    @sow = Sow.find(params[:id])
    @contract = @sow.contract
    if session[:user].nil? 
      redirect_to :controller => "login", :action => "new"
    else
      @sow.updated_by = session[:user]
    end
    @sow.deleted = true
    @sow.save
    #@sow.destroy

    respond_to do |format|
      format.html {redirect_to clients_path(:clientid => @sow.contract.client_id)}
      #format.html { redirect_to contract_sows_path(@contract) }
      format.json { head :ok }
    end
  end
end

app/helpers/sows_helper.rb
module SowsHelper
	def exclude_column(col)
		result = case col
		   when "id" then false
		   when "created_at" then false
		   when "updated_at" then false
		   when "status" then false
		   when "version" then false
		   when "sow_id" then false
		   else true
		end
		return result
	end

	def us_states
	    [
	      ['Alabama', 'AL'],
	      ['Alaska', 'AK'],
	      ['Arizona', 'AZ'],
	      ['Arkansas', 'AR'],
	      ['California', 'CA'],
	      ['Colorado', 'CO'],
	      ['Connecticut', 'CT'],
	      ['Delaware', 'DE'],
	      ['District of Columbia', 'DC'],
	      ['Florida', 'FL'],
	      ['Georgia', 'GA'],
	      ['Hawaii', 'HI'],
	      ['Idaho', 'ID'],
	      ['Illinois', 'IL'],
	      ['Indiana', 'IN'],
	      ['Iowa', 'IA'],
	      ['Kansas', 'KS'],
	      ['Kentucky', 'KY'],
	      ['Louisiana', 'LA'],
	      ['Maine', 'ME'],
	      ['Maryland', 'MD'],
	      ['Massachusetts', 'MA'],
	      ['Michigan', 'MI'],
	      ['Minnesota', 'MN'],
	      ['Mississippi', 'MS'],
	      ['Missouri', 'MO'],
	      ['Montana', 'MT'],
	      ['Nebraska', 'NE'],
	      ['Nevada', 'NV'],
	      ['New Hampshire', 'NH'],
	      ['New Jersey', 'NJ'],
	      ['New Mexico', 'NM'],
	      ['New York', 'NY'],
	      ['North Carolina', 'NC'],
	      ['North Dakota', 'ND'],
	      ['Ohio', 'OH'],
	      ['Oklahoma', 'OK'],
	      ['Oregon', 'OR'],
	      ['Pennsylvania', 'PA'],
	      ['Puerto Rico', 'PR'],
	      ['Rhode Island', 'RI'],
	      ['South Carolina', 'SC'],
	      ['South Dakota', 'SD'],
	      ['Tennessee', 'TN'],
	      ['Texas', 'TX'],
	      ['Utah', 'UT'],
	      ['Vermont', 'VT'],
	      ['Virginia', 'VA'],
	      ['Washington', 'WA'],
	      ['West Virginia', 'WV'],
	      ['Wisconsin', 'WI'],
	      ['Wyoming', 'WY']
	    ]
	end
end

app/views/sows/_autointel.html.erb
  <% if sow.autointel_rates.empty? %>
     <% sow.autointel_rates.build %>
  <% else %>
     <% sow.autointel_rates.build(sow.autointel_rates.last.dup.attributes) %>
  <% end %>
 
  
  <%= f.fields_for :autointel_rates, sow.autointel_rates.last do |fa| %>
 
      <div class="field"  id="autointel_type">
        <%= fa.label :maintype,"Type" %>
        <%= fa.select  :maintype, [['Per Hit'],['Contingency']], :prompt=>"Select" %><br /><br /><br />
        <%= fa.hidden_field :version, :value => (@sow.version.to_i + 1) %>
      </div>


      <table id='autointel_table'>
        <thead>
          <th></th>
          <th class="tablesign"></th>
          <th></th>
          <th class="tablesign"></th>
          <th></th>
          <th class="tablesign"></th>
          <th></th>
          <th class="tablesign"></th>
        </thead>
        <tbody>
          <% state_index = 0 %>
          <% column_num = 4 %>
          <% row_num = ( us_states.length.to_f / column_num ).ceil %>
          <% row_num.times do %>
            <tr>
              
                <% if state_index < us_states.length %>
                  <td style="width: 150px;text-align:right;">
                    <%= us_states[state_index][0] %>
                  </td> 
                  <td>
                    <%= fa.text_field us_states[state_index][1].to_sym,  :style => "color: red; width: 150px;margin: 10px",:class => "stateinput" %>
                  </td>  
                <% else %>
                  <td></td><td></td>
                <% end %>

                <% if (state_index + row_num) < us_states.length %>
                  <td style="width: 250px;text-align:right;">
                    <%= us_states[state_index + row_num][0] %>
                  </td> 
                  <td>
                    <%= fa.text_field us_states[state_index + row_num][1].to_sym,  :style => "color: red; width: 150px;margin: 10px",:class => "stateinput" %>
                  </td>  
                <% else %>
                  <td></td><td></td>
                <% end %>

                <% if (state_index + 2 * row_num) < us_states.length %>
                  <td style="width: 150px;text-align:right;">
                    <%= us_states[state_index + 2 * row_num][0] %>
                  </td> 
                  <td>
                    <%= fa.text_field us_states[state_index + 2 * row_num][1].to_sym,  :style => "color: red; width: 150px;margin: 10px",:class => "stateinput" %>
                  </td>  
                <% else %>
                  <td></td><td></td>
                <% end %>
                
                 <% if (state_index + 3 * row_num) < us_states.length %>
                  <td style="width: 150px;text-align:right;">
                    <%= us_states[state_index + 3 * row_num][0] %>
                  </td> 
                  <td>
                    <%= fa.text_field us_states[state_index + 3 * row_num][1].to_sym, :style => "color: red; width: 150px;margin: 10px",:class => "stateinput" %>
                  </td>  
                <% else %>
                  <td></td><td></td>
                <% end %>
            </tr>
            <% state_index = state_index + 1 %>
          <% end %>
        </tbody>
      </table>
     
   <% end %><br />


   <script>
  function hide_table() {
    $("#autointel_table").hide();
  }


  $(function(){

     if ($("#autointel_type  option:selected").text().toLowerCase() == "per hit" ) {
       $(".tablesign").each(function() { $(this).html('$');});
       $("#autointel_table").show();
     } else  if (  $(".autointel_type  option:selected").text().toLowerCase() == "contingency" ) {
       $(".tablesign").each(function() { $(this).html('%');});
       $("#autointel_table").show();
     } else {
       $("#autointel_table").hide();
     }

     $("#autointel_type").bind("change", function () {
        hide_table();
        
          if ($("#autointel_type option:selected").text().toLowerCase() == "per hit" ) {
            $("#autointel_table").show();
            $(".tablesign").each(function() { $(this).html('$');});
            $(".stateinput").each(function() { $(this).val(''); });
          } else if($("#autointel_type option:selected").text().toLowerCase() == "contingency" ) {
              $("#autointel_table").show();
              $(".tablesign").each(function() { $(this).html('%');});
              $(".stateinput").each(function() { $(this).val(''); });
          } else {
            return;
          }
    });

  });

</script>

app/views/sows/_charity.html.erb
  <% if sow.charity_rates.empty? %>
     <% sow.charity_rates.build %>
  <% else %>
     <% sow.charity_rates.build(sow.charity_rates.last.dup.attributes) %>
  <% end %>
 
  
  <%= f.fields_for :charity_rates, sow.charity_rates.last do |fa| %>
 
      <div id="score_charity">
        <div class="field">
          <%= fa.label :chmons, "Charity Monthly Fee ($)" %> 
          <%= fa.text_field :subscription_fee  %>
        </div><br /><br /><br />
        <div class="field">
          <%= fa.label :chtrans, "Charity Transaction Fee ($)" %>
          <%= fa.text_field :transaction_fee  %>
          <%= fa.hidden_field :version, :value => (@sow.version + 1) %>
        </div><br /><br /><br />
      </div>
     
   <% end %><br />


   

app/views/sows/_payment.html.erb
  <% if sow.payment_rates.empty? %>
     <% sow.payment_rates.build %>
  <% else %>
     <% sow.payment_rates.build(sow.payment_rates.last.dup.attributes) %>
  <% end %>
 
  
  <%= f.fields_for :payment_rates, sow.payment_rates.last do |fa| %>
 
      <div id="score_payment">
        <div class="field">
          <%= fa.label "Payment Monthly Fee ($)" %> 
          <%= fa.text_field :subscription_fee  %>
        </div><br /><br /><br />
        <div class="field">
          <%= fa.label "Payment Transaction Fee ($)" %>
          <%= fa.text_field :transaction_fee  %>
          <%= fa.hidden_field :version, :value => (@sow.version + 1) %>
        </div><br /><br /><br />
      </div>
     
   <% end %><br />


   

app/views/sows/edit.html.erb
<div class="span3">

      <!--Sidebar content-->
      <br /><br /><br />
       <div class="well sidebar-nav">
        <h3>Contract Details</h3>
        <table id="tb" class="table  table-condensed table-hover " cellspacing="0">
 
            <tbody>
                <tr>
                    <td class='hed'>Client name: </td>
                    <td><%= @contract.client.name %> </td>
                </tr>
                <tr>
                    <td class='hed'>Client state: </td>
                    <td><%= @contract.client.state %> </td>
                </tr>
                <tr>
                    <td class='hed'>Real cust_id: </td>
                    <td><%= @contract.client.cust_id  %>  </td>
                </tr>
                <!--
                <tr>
                    <div>         
                        <button id="enable" class="btn btn-primary">enable/disable edit</button>
                    </div>  
                </tr>
                -->
            </tbody>
        </table> 
        <h3>Existing SOWs</h3>
        <table id="tb" class="table  table-condensed table-hover " cellspacing="0">
 
            <tbody>
                 <% @contract.sows.each do |s| %>
                     <tr>  
                        <td class='hed '><span class="label label-success"> <%= Product.find(s.product_id).name.upcase %> </span></td>  
                    </tr>
                <% end %>
            </tbody>
        </table> 

        <hr>
        	<div class="span2">
                     <%= link_to  clients_path(:clientid => @contract.client_id), :action => "index", :class=>"btn btn-small", :method => :get do%>
                     <i class="icon-arrow-left" ></i> Back to Client
                     <% end %>
            </div><br /><br /><br />
            <div class="span2">
                <%= link_to  contracts_url(:cid=>@contract.client.id, :history=>'current'),:class=>"btn btn-small ", :method => :get do%>
                 <i class="icon-arrow-left" ></i> Back to Contract
                <% end %>
            </div><br /><br /><br />
            <div class="span2">
                <%= link_to  contract_sows_path(@contract),:class=>"btn btn-small ", :method => :get do%>
                 <i class="icon-arrow-left" ></i> Back to SOW
                <% end %>
            </div>
 <br /><br /><br /><br />
      </div><!--/.well -->
</div>

<div class="span1">
</div>

<div class="span8">

<br /><br /><br />
<h1>Editing sow</h1>

<%= render 'form' %>
 
</div>

app/views/sows/index.html.erb
<br /><br />
<div class="row">
<div class="span3">

      <!--Sidebar content-->

       <div class="well sidebar-nav">

        <h3>Contract details</h3>
        <table id="tb" class="table  table-condensed table-hover " cellspacing="0">

            <tbody>
                <tr>
                    <td class='hed'>Client name: </td>
                    <td><%= @contract.client.name %> </td>
                </tr>
                <tr>
                    <td class='hed'>Client state: </td>
                    <td><%= @contract.client.state %> </td>
                </tr>
                <% @contract.client.salespeople.each do |person|  %> 
                <tr>
                        <td class='hed'>Sales: </td>
                        <td><%= person.first_name + " " + person.last_name  %>  </td>
                </tr>
                <% end  %>    
                <tr>
                    <td class='hed'>Real cust_id: </td>
                    <td>
                        <% if @contract.client.cust_id.nil? %>
                           N/A
                        <% else %>
                            <%= @contract.client.cust_id  %> 
                        <% end %>
                    </td>
                </tr>
                
                <tr>
                    <td class='hed'>Contract sign date: </td>
                    <td>
                         <div id="contract_sign_at" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= @contract.id%>" data-value = "<%= @contract.contract_sign_at %>" >
                        </div>
                    </td>
                </tr>

                <% if false %>

                <% if @contract.ca_flag == '1' %>
                    <tr>
                        <td class='hed'>CA: </td>
                        <td>
                             <div id="ca_date" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= @contract.id %>" data-value = "<%= @contract.ca_date %>" >
                            </div>
                        </td>
                    </tr>
                <% end %>
                 <% if @contract.nda_flag == '1' %>
                    <tr>
                        <td class='hed'>NDA: </td>
                        <td>
                             <div id="nda_date" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= @contract.id %>" data-value = "<%= @contract.nda_date %>" >
                            </div>
                        </td>
                    </tr>
                <% end %>
                <tr>
                    <td class='hed'>Contract execute date: </td>
                    <td>
                         <div id="contract_execute_date" class="ct_date" data-resource="contract" data-type="date" data-pk="1"  data-url="/contracts/<%= @contract.id %>" data-value = "<%= @contract.contract_execute_date %>" >
                        </div>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table> 
        <div class="span2">
            <%= link_to  clients_path(:clientid => @contract.client_id), :action => "index", :class=>"btn btn-small", :method => :get do%>
                 <i class="icon-arrow-left" ></i> Back to Client
            <% end %>
        </div><br /><br /><br />
        <div class="span2">
            <%= link_to  contracts_url(:cid=>@contract.client.id, :history=>'current'),:class=>"btn btn-small ", :method => :get do%>
             <i class="icon-arrow-left" ></i> Back to Contract
            <% end %>
        </div><br /><br /><br />
      </div><!--/.well -->
</div>
 
<div class="span8-fluid">
<!--Body content-->

<h1>Listing SOWs </h1><br /><br />
    <!-- <div>         
        <button id="enable" class="btn btn-primary">enable/disable edit</button>
    </div> -->
<br />
<% if @sows.empty? %> 
    <div class="notice"> You do not have any SOW currently. please add one! </div>
<% else %>
        <% @sows.each do |sow| %>
              <table id="tb" class=" stats"  >
                <thead>
                <tr>
                    <th class='hed'>Product </th>
                    <th class='hed'>Version </th>
                    <th class='hed'>Details </th>
                </tr>
                </thead>

                    <% sow.sow_files.each do |file| %>
                        <tr>
                            <td>
                                <%= Product.find(sow.product_id).name.upcase %>
                            </td>
                            <td>
                                <%= " V#{file.version}" %>
                                <%= link_to raw('<i class=" icon-download " ></i>'), download_sow_path(sow, :version=>file.version) %>
                                
                            </td>
                          
                            <td>
                                <% if  Product.find(sow.product_id).name.upcase == 'PAYORINTEL' %>
                                    <% t = sow.payorintel_rates %> 
                                <% elsif Product.find(sow.product_id).name.upcase == 'AUTOINTEL'%>
                                    <% t = sow.autointel_rates %> 
                                <% elsif Product.find(sow.product_id).name.upcase =~ /PAYMENT/  %>
                                    <% t = sow.payment_rates %> 
                                <% elsif  Product.find(sow.product_id).name.upcase =~ /CHARITY/ %>
                                    <% t = sow.charity_rates %> 
                                <% end %>
                                
                                <% t.each do |certain_details| %>
                                  <% if certain_details.version == file.version %>
                                    <%= certain_details.details %>
                                  <% end %>
                                <% end %>
                                 
                            </td>  
                        </tr> 
                    <% end %>
              </table>      
       <% end %>
<% end %>
<br /><br /><br />

</div>

<!--          <div>
           <p> <%= button_to "New Sow", new_contract_sow_path(@contract), :method => "get" %>  </p>
        </div> -->


<script>
 
    $(function(){
        $('.ct_date').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            format: 'yyyy-mm-dd',    
            viewformat: 'mm/dd/yyyy',    
            datepicker: {
                    weekStart: 1
            }

        });
        $('#enable').click(function() {
            $('#tb .editable').editable('toggleDisabled');
        });  
        $('.ct_description').editable({
            ajaxOptions: {
                type: 'PUT'
            },
            title: 'Enter Description',

        });

        
        $('.sow_date').editable({
            format: 'yyyy-mm-dd',    
            viewformat: 'dd/mm/yyyy',    
            mode: 'inline',
            datepicker: {
                    weekStart: 1
               }
        });

        $('.sow_yn').editable({
            source: [
                  {value: 'Y', text: 'Y'},
                  {value: 'N', text: 'N'},
               ]
        });

        $('.sow_int').editable({
            mode: 'inline',
            source: [
                  {value: 1, text: '1'},
                  {value: 2, text: '2'},
                  {value: 3, text: '3'},
                  {value: 4, text: '4'},
                  {value: 5, text: '5'},
                  {value: 6, text: '6'},
                  {value: 7, text: '7'},
                  {value: 8, text: '8'},
                  {value: 9, text: '9'},
                  {value: 10, text: '10'},
                  {value: 11, text: '11'},
                  {value: 12, text: '12'},
                  {value: 13, text: '13'},
                  {value: 14, text: '14'},
                  {value: 15, text: '15'},
               ]
        });

        $('#tb .editable').editable('toggleDisabled');

    });
</script>
   

</div>

app/views/sows/new.html.erb
<div class="span3">

      <!--Sidebar content-->
      <br /><br /><br />
       <div class="well sidebar-nav">
        <h3>Contract Details</h3>
        <table id="tb" class="table  table-condensed table-hover " cellspacing="0">
 
            <tbody>
                <tr>
                    <td class='hed'>Client name: </td>
                    <td><%= @contract.client.name %> </td>
                </tr>
                <tr>
                    <td class='hed'>Client state: </td>
                    <td><%= @contract.client.state %> </td>
                </tr>
                <tr>
                    <td class='hed'>Real cust_id: </td>
                    <td><%= @contract.client.cust_id  %>  </td>
                </tr>
                <!--
                <tr>
                    <div>         
                        <button id="enable" class="btn btn-primary">enable/disable edit</button>
                    </div>  
                </tr>
                -->
            </tbody>
        </table> 
        <h3>Existing SOWs</h3>
        <table id="tb" class="table  table-condensed table-hover " cellspacing="0">
 
            <tbody>
                 <% @contract.sows.each do |s| %>
                     <tr>  
                        <td class='hed '><span class="label label-success"> <%= Product.find(s.product_id).name.upcase %> </span></td>  
                    </tr>
                <% end %>
            </tbody>
        </table> 

        <hr>

             <div class="span2">
                     <%= link_to  clients_path(:clientid => @contract.client_id), :action => "index", :class=>"btn btn-small", :method => :get do%>
                     <i class="icon-arrow-left" ></i> Back to Client
                     <% end %>
            </div><br /><br /><br />
            <div class="span2">
                <%= link_to  contracts_url(:cid=>@contract.client.id, :history=>'current'),:class=>"btn btn-small ", :method => :get do%>
                 <i class="icon-arrow-left" ></i> Back to Contract
                <% end %>
            </div><br /><br /><br />
            <div class="span2">
                <%= link_to  contract_sows_path(@contract),:class=>"btn btn-small ", :method => :get do%>
                 <i class="icon-arrow-left" ></i> Back to SOW
                <% end %>
            </div>
 <br /><br /><br /><br />
      </div><!--/.well -->
</div>

<div class="span6">
<!--Body content-->

    
     
     <br /><br /><br />
    <div id="container" class="container-fluid">
 
		<h1>New SOW</h1>

		<%= render 'form' %>


	</div>
            
</div>

<script>

            $(function(){
                $('.ct_date').editable({
                    ajaxOptions: {
                        type: 'PUT'
                    },
                    format: 'yyyy-mm-dd',    
                    viewformat: 'dd/mm/yyyy',    
                    datepicker: {
                            weekStart: 1
                    }

                });
                $('#enable').click(function() {
                    $('#tb .editable').editable('toggleDisabled');
                });  
                $('.ct_description').editable({
                    ajaxOptions: {
                        type: 'PUT'
                    },
                    title: 'Enter Description',

                });
                        $('#tb .editable').editable('toggleDisabled');
            });
 </script>

app/views/sows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sow ko date:</b>
  <%= @sow.sow_ko_date %>
</p>

<p>
  <b>Sow production date:</b>
  <%= @sow.sow_production_date %>
</p>

<p>
  <b>Sow start date:</b>
  <%= @sow.sow_start_date %>
</p>

<p>
  <b>Sow end date:</b>
  <%= @sow.sow_end_date %>
</p>

<p>
  <b>Auto renew:</b>
  <%= @sow.auto_renew %>
</p>

<p>
  <b>Accept term:</b>
  <%= @sow.accept_term %>
</p>

<p>
  <b>Renewal:</b>
  <%= @sow.renewal %>
</p>

<p>
  <b>Renew times:</b>
  <%= @sow.renew_times %>
</p>

<p>
  <b>Product:</b>
  <%= @sow.product_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @sow.comment %>
</p>


<%= link_to 'Edit', edit_sow_path(@sow) %> |
<%= link_to 'Back', sows_path %>