config/routes.rb
ManagerTool::Application.routes.draw do
  root :to => "clients#index"
  get "login/new"
  post "login/check" => "login#check"

  resources :contracts  do 
    resources :sows, shallow: true

     member do
      get  :download
    end
  end
 
  resources :sows do
     member do
      get  :download
    end
  end

  resources :sow_details

  resources :products

  resources :clients do
    member do
      get  :download
    end
  end

  resources :contracts

  resources :salespeople

  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true

	def formal_name
		name.upcase
	end

	def self.find_all_not_in(ids)
		if ids.empty?
			find :all
		else
  			find :all, :conditions => ["id NOT IN (?)", ids]
  		end
	end

	def self.find_all_in(ids)
		ids.delete_if {|x| x == nil}
		if ids.empty?   
			find :all 
		else
  			find :all, :conditions => ["id IN (?)", ids]
  		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    session[:current] = 'menu_admin'
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    session[:current] = 'menu_admin'
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    session[:current] = 'menu_admin'
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    @product.subscription_fee = @product.score
    @product.transaction_fee  = @product.score
    @product.commercial_rate  = ! @product.score
    @product.medicaid_rate    = ! @product.score
    @product.medicare_rate    = ! @product.score
    @product.global_rate      = ! @product.score


    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    if params[:product][:score] == 0
      score_flag = false
    end
    @product.subscription_fee = score_flag
    @product.transaction_fee  = score_flag
    @product.commercial_rate  = ! score_flag
    @product.medicaid_rate    = ! score_flag
    @product.medicare_rate    = ! score_flag
    @product.global_rate      = ! score_flag

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_url, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Product Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
        <%= f.label :Type %>
        <%= f.label :Score %>
        <%= f.check_box :score, :title => "score", :style => "float:left;" %>
      </div><br /><br /><br /><br />
      
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="span1">
      <!--Sidebar content-->
 
</div>

<div class="span10">
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="span1">
      <!--Sidebar content-->
 
</div>



<div class="span10">
  <br /><br /><br />
<h2 class="my_h2">Listing products</h2>

<!--Body content-->
 

<table   class="stats" style="width: 100%">
    <thead>
      <tr>
        <th class="hed">Name </th>
        <th class="hed">Type </th>
      <!--   <th class="hed">Medicaid </th>
        <th class="hed">Medicare</th>
        <th class="hed">Commercial</th>
        <th class="hed">Global </th>
        <th class="hed">Subscription_fee</th>
        <th class="hed">Transaction_fee</th> -->
        <th class="hed">Edit</th>
        <th class="hed">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td>
              <% if product.score %>
                 score
              <% else %>
                non-score
              <% end %>
          </td>
         <!--  <td>
              <% if product.medicaid_rate %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td>
          <td>
              <% if product.medicare_rate  %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td>
          <td>
              <% if product.commercial_rate %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td>
          <td>
              <% if product.global_rate %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td>
          <td>
              <% if product.transaction_fee %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td>
          <td>
              <% if product.subscription_fee  %>
                <i class="icon-ok"></i>
              <% else %>
                <i class="icon-remove"></i>
              <% end %>
          </td> -->

          <td><%= link_to raw('<i class="icon-edit"></i>'), edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br />

 
</div>
 

app/views/products/new.html.erb
<div class="span1">
</div>

<div class="span11">
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>
 
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>